### ISSUE TITLE
Invalid email address embedded@1nce.com

### ISSUE THREAD

**Issue by zzasada** [1NCE-GmbH/blueprint-zephyr#1]
The email at the end of the readme "embedded@1nce.com" is invalid. I tried emailing a request to it earlier and the email gets returned with

<html>
<body>

Your message to embedded@1nce.com couldn't be delivered.
--
embedded wasn't found at 1nce.com.

</body>
</html>

**Comment by jamali005** [comment]
Hi, thanks for bringing this up! This issue has been fixed.
Closing this issue out. Feel free to re-open it if you have any related followup questions.
